### ISSUE TITLE
Comparing file descriptor to 1 instead of -1

### ISSUE THREAD

**Issue by ZeanZarzin** [aautin/42_so_long#1]
At line 32 in `src/image.c`, the result of `open` is compared to 1 instead of -1 to check if it was opened:
```c
int fd;

fd = open(ft_strnstr(imgs_name[i], "sprites", len), O_RDONLY);
if (fd != 1) // here
```
File descriptor 1 is the standard output (`STDOUT_FILENO`), so it will never be returned by `open`.
If `open` does fail, it returns -1, so the code wouldn't see that it failed to open.

**Comment by aautin** [comment]
Ohw yes! I got it, what a clumsy mistake! I'll fix that now
