### ISSUE TITLE
Segmentation fault when argc != 2 (minor issue)

### ISSUE THREAD

**Issue by ZeanZarzin** [aautin/42_so_long#2]
When the program isn't given exactly one command line argument, it will not allocate anything, but still tries to `do_free_game`.
This causes it to try to use `free_stab` on `game->map`, which is undefined.

```c
void	free_stab(char **str)
{
	int	i;

	i = 0;
	while (str[i]) // error here: tries to dereference an undefined pointer (most likely just NULL)
	{
		free(str[i]);
		i++;
	}
	free(str);
}
```

**Comment by aautin** [comment]
Hey, got it ! :)
I'll move the call of this function in the argc == 2 scope
Thanks for real!
