### ISSUE TITLE
Any map can be considered "rectangular"

### ISSUE THREAD

**Issue by ZeanZarzin** [aautin/42_so_long#5]
This is how a map is determined to be a rectangle:
```c
while (file_content[i])
{
	if (file_content[i] == '\n' && ((i - size.y++) % size.x != 0)) // important part
	{
		// not rectangular, shut program down
	}
	i++;
}
// it's a rectangle, keep going
```
meaning that if `(i - size.y++)` is a multiple of `size.x`, it doesn't error.

Because `size.x` is just the width of the first row, if the first row is just one character, any width will be accepted for the rest of the file. Later on this might also lead to problems with the pathfinding, and the check that makes sure the map is surrounded by 1s.

**Comment by ZeanZarzin** [comment]
oh, and an issue so minor it doesn't really deserve its own issue: in the same file (src/parsing.c) at line 21, it does `mapfile + (len - 4)`, not taking into account that the length may be less than 4

**Comment by aautin** [comment]
> oh, and an issue so minor it doesn't really deserve its own issue: in the same file (src/parsing.c) at line 21, it does `mapfile + (len - 4)`, not taking into account that the length may be less than 4

Ohw yes! I verified this case for the .ber images but not for the .ber maps, I fixed it !


> This is how a map is determined to be a rectangle:
> 
> ```c
> while (file_content[i])
> {
> 	if (file_content[i] == '\n' && ((i - size.y++) % size.x != 0)) // important part
> 	{
> 		// not rectangular, shut program down
> 	}
> 	i++;
> }
> // it's a rectangle, keep going
> ```
> 
> meaning that if `(i - size.y++)` is a multiple of `size.x`, it doesn't error.
> 
> Because `size.x` is just the width of the first row, if the first row is just one character, any width will be accepted for the rest of the file. Later on this might also lead to problems with the pathfinding, and the check that makes sure the map is surrounded by 1s.

What you meant is clever, it needs a complement part in the condition of `if (file_content[i] == '\n' && ((i - size.y++) % size.x != 0))`
Let me think about it...

**Comment by aautin** [comment]
> This is how a map is determined to be a rectangle:
> 
> ```c
> while (file_content[i])
> {
> 	if (file_content[i] == '\n' && ((i - size.y++) % size.x != 0)) // important part
> 	{
> 		// not rectangular, shut program down
> 	}
> 	i++;
> }
> // it's a rectangle, keep going
> ```
> 
> meaning that if `(i - size.y++)` is a multiple of `size.x`, it doesn't error.
> 
> Because `size.x` is just the width of the first row, if the first row is just one character, any width will be accepted for the rest of the file. Later on this might also lead to problems with the pathfinding, and the check that makes sure the map is surrounded by 1s.

I put the modulo idea aside, and I tried to simplify the calcul :
before:
```
if (file_content[i] == '\n' && ((i - size.y++) % size.x != 0))
		{
			free(file_content);
			do_msg_exit("The map isn't a rectangle");
		}
		i++;
```
now:
```
if (file_content[i] == '\n' && (i != ((size.y + 1) * size.x) + size.y))
		{
			free(file_content);
			do_msg_exit("The map isn't a rectangle");
		}
		size.y += file_content[i] == '\n';
		i++;
```
My condition explanations :
if we are arrived at the end of a line (on a \n) and that the current index is unequal to the number of line*firs_line_len so this current line I just arrived at the end has a different len.
So : the map isn't a rectangle

**Comment by ZeanZarzin** [comment]
`((size.y + 1) * size.x) + size.y` is wrong, but the current implementation, `(size.y * size.x) + size.y - 1` does seem to work!
Although I'm not quite sure if you came up with this new version by thinking about it or by trying stuff and seeing what works, because the way it's written looks kind of odd (that and the fact that it was changed in a commit called "wieru")...

Personally, I'd write it as: `(size.y * (size.x + 1)) - 1`, because although each line looks `size.x` characters wide, if we include the newline, it's actually `size.x+1` characters long in memory. Then, because indices start at 0 and not at 1, we substract 1.

That being said, the way I'd usually solve this kind of problem would just be using a `current_x` variable that resets when it finds a newline, it's much easier to simply count up and check if the counter is equal to something.

**Comment by aautin** [comment]
I agree, I kinda thought from the opposite way : lets add the number of times I browse on a newline, so let's add size.y (I concede that the following -1 was just the result of trying and see).
So `(size.y * size.x) + size.y` is equivalent to `(size.y * (size.x + 1))`

Thought, I will use your equation 'cause I understand that this one seems way more logical.
